# Generated by Django 5.0.1 on 2026-03-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientstatus_client_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientstatus',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Client Status', 'verbose_name_plural': 'Client Statuses'},
        ),
        migrations.AddField(
            model_name='clientstatus',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
