# Generated by Django 5.0.1 on 2026-03-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
    ]
